### ISSUE TITLE
GPU Not Supported Crashes the App

### ISSUE THREAD

**Issue by mleo2003** [Lenochxd/WebDeck#38]
**Describe the bug**
It seems my older Nvidia GPU is causing nvml to raise a "Not Supported" exception, which is then causing another error.

**To Reproduce**
Sadly, this may be limited to older hardware.

**Expected behavior**
I was hoping I could at least configure the application to ignore my GPU, to continue to work at a basic level.

**Screenshots**
![image](https://github.com/user-attachments/assets/04eb3ffb-ab37-4e71-ab38-376d71183d58)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: N/A, happens upon app startup
 - Version: latest release

**Smartphone (please complete the following information):**
 - Device: N/A, this happens on the desktop before any mobile device is involved

**Additional context**
I can tell you the Model of my GPU, but I know it is old enough it is not generally supported by most newer libs.

**Comment by Lenochxd** [comment]
Hey :)

Thank you for your detailed report. To temporarily resolve this issue, you can manually edit the `config.json` file and set the `gpu_method` setting to `"None"`. This will ignore the error. https://github.com/Lenochxd/WebDeck/issues/7#issuecomment-1964707973

The application has been completely rewritten since version 1.8.7, and this issue will be fixed in the next release. If the workaround doesn't help, you can try building the application yourself using `build.bat`, if you are comfortable doing so.

**Comment by mleo2003** [comment]
Many thanks, that actually did the trick to disable GPU usage.

**Comment by Lenochxd** [comment]
Perfect!
